
public class Custom_details extends javax.swing.JFrame {

 public Custom_details() {
        initComponents();
        this.setLocationRelativeTo(null);
 }
    String passengers;
    
    public Custom_details(String n) {
        initComponents();
        this.setLocationRelativeTo(null);
        passengers = n;
        //System.out.println("ghvgvu"+h.passengers);
        switch(passengers)
        {
            case "1":
            {
             disable();
                 p1.setEnabled(true);
                p1_age.setEnabled(true);
                p1_agefield.setEnabled(true);
                p1_fname.setEnabled(true);
                p1_lastfield.setEnabled(true);
                p1_namefield.setEnabled(true);
                p1_star.setEnabled(true);
                p1_star2.setEnabled(true);
                p1_star3.setEnabled(true);
                p1_star4.setEnabled(true);
                p1_type.setEnabled(true);
                p1_typefield.setEnabled(true); 
            }break;
            case "2":
            {
                  disable();
                 p1.setEnabled(true);
                p1_age.setEnabled(true);
                p1_agefield.setEnabled(true);
                p1_fname.setEnabled(true);
                p1_lastfield.setEnabled(true);
                p1_namefield.setEnabled(true);
                p1_star.setEnabled(true);
                p1_star2.setEnabled(true);
                p1_star3.setEnabled(true);
                p1_star4.setEnabled(true);
                p1_type.setEnabled(true);
                p1_typefield.setEnabled(true); 
                  p2.setEnabled(true);
                p2_age.setEnabled(true);
                p2_agefield.setEnabled(true);
                p2_fname.setEnabled(true);
                p2_lastfield.setEnabled(true);
                p2_namefield.setEnabled(true);
                p2_star.setEnabled(true);
                p2_star2.setEnabled(true);
                p2_star3.setEnabled(true);
                p2_star4.setEnabled(true);
                p2_type.setEnabled(true);
                p2_typefield.setEnabled(true);
            }break;
            case "3":
            {
                        p4.setEnabled(false);
                p4_age.setEnabled(false);
                p4_agefield.setEnabled(false);
                p4_fname.setEnabled(false);
                p4_lastfield.setEnabled(false);
                p4_namefield.setEnabled(false);
                p4_star.setEnabled(false);
                p4_star2.setEnabled(false);
                p4_star3.setEnabled(false);
                p4_star4.setEnabled(false);
                p4_type.setEnabled(false);
                p4_typefield.setEnabled(false);
            }break;
            default:
            {
                System.out.println("Not.....");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        p1_age = new javax.swing.JLabel();
        p1_star3 = new javax.swing.JLabel();
        p1_agefield = new javax.swing.JComboBox<>();
        p1_type = new javax.swing.JLabel();
        p1_star4 = new javax.swing.JLabel();
        p1_typefield = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        p1 = new javax.swing.JLabel();
        p1_lastfield = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        p1_star2 = new javax.swing.JLabel();
        p1_namefield = new javax.swing.JTextField();
        p1_fname = new javax.swing.JLabel();
        p1_star = new javax.swing.JLabel();
        p2_star = new javax.swing.JLabel();
        p2_fname = new javax.swing.JLabel();
        p2_namefield = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        p2_star2 = new javax.swing.JLabel();
        p2_lastfield = new javax.swing.JTextField();
        p2_star3 = new javax.swing.JLabel();
        p2_age = new javax.swing.JLabel();
        p2_agefield = new javax.swing.JComboBox<>();
        p2_star4 = new javax.swing.JLabel();
        p2_type = new javax.swing.JLabel();
        p2_typefield = new javax.swing.JComboBox<>();
        p2 = new javax.swing.JLabel();
        p3_star4 = new javax.swing.JLabel();
        p3_star = new javax.swing.JLabel();
        p3_star3 = new javax.swing.JLabel();
        p3_agefield = new javax.swing.JComboBox<>();
        p3 = new javax.swing.JLabel();
        p3_namefield = new javax.swing.JTextField();
        p3_fname = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        p3_lastfield = new javax.swing.JTextField();
        p3_type = new javax.swing.JLabel();
        p3_star2 = new javax.swing.JLabel();
        p3_typefield = new javax.swing.JComboBox<>();
        p3_age = new javax.swing.JLabel();
        p4_age = new javax.swing.JLabel();
        p4_star3 = new javax.swing.JLabel();
        p4_type = new javax.swing.JLabel();
        p4_lastfield = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        p4_namefield = new javax.swing.JTextField();
        p4_fname = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p4_star2 = new javax.swing.JLabel();
        p4_star4 = new javax.swing.JLabel();
        p4_star = new javax.swing.JLabel();
        p4_agefield = new javax.swing.JComboBox<>();
        p4_typefield = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 800));
        jPanel1.setSize(new java.awt.Dimension(1100, 800));

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/bhavesh/Downloads/logo.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(800, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(174, 29, 33));
        jPanel3.setPreferredSize(new java.awt.Dimension(1100, 100));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Passenger Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setText("Passenger");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel4.setText("Contact details");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("TITLE");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MR", "MRS" }));
        jComboBox2.setMaximumSize(new java.awt.Dimension(32767, 0));
        jComboBox2.setPreferredSize(new java.awt.Dimension(96, 100));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("First Name");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Last Name");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Phone no.");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("*");

        p1_age.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p1_age.setForeground(new java.awt.Color(204, 204, 204));
        p1_age.setText("Age");

        p1_star3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p1_star3.setForeground(new java.awt.Color(204, 0, 0));
        p1_star3.setText("*");

        p1_agefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", " " }));
        p1_agefield.setMaximumSize(new java.awt.Dimension(32767, 0));
        p1_agefield.setPreferredSize(new java.awt.Dimension(96, 100));

        p1_type.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p1_type.setForeground(new java.awt.Color(204, 204, 204));
        p1_type.setText("Type");

        p1_star4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p1_star4.setForeground(new java.awt.Color(204, 0, 0));
        p1_star4.setText("*");

        p1_typefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Children", "Senior Citizen", "Indian Armed Forces" }));
        p1_typefield.setMaximumSize(new java.awt.Dimension(32767, 0));
        p1_typefield.setPreferredSize(new java.awt.Dimension(96, 100));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Email");

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("*");

        jCheckBox1.setText("I prefer not to receive future communication and newsletter from Skylanes.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(174, 29, 33));

        p1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        p1.setText("Passenger 1");

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Last Name");

        p1_star2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p1_star2.setForeground(new java.awt.Color(204, 0, 0));
        p1_star2.setText("*");

        p1_fname.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p1_fname.setForeground(new java.awt.Color(204, 204, 204));
        p1_fname.setText("First Name");

        p1_star.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p1_star.setForeground(new java.awt.Color(204, 0, 0));
        p1_star.setText("*");

        p2_star.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p2_star.setForeground(new java.awt.Color(204, 0, 0));
        p2_star.setText("*");

        p2_fname.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p2_fname.setForeground(new java.awt.Color(204, 204, 204));
        p2_fname.setText("First Name");

        jLabel33.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Last Name");

        p2_star2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p2_star2.setForeground(new java.awt.Color(204, 0, 0));
        p2_star2.setText("*");

        p2_star3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p2_star3.setForeground(new java.awt.Color(204, 0, 0));
        p2_star3.setText("*");

        p2_age.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p2_age.setForeground(new java.awt.Color(204, 204, 204));
        p2_age.setText("Age");

        p2_agefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", " " }));
        p2_agefield.setMaximumSize(new java.awt.Dimension(32767, 0));
        p2_agefield.setPreferredSize(new java.awt.Dimension(96, 100));
        p2_agefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2_agefieldActionPerformed(evt);
            }
        });

        p2_star4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p2_star4.setForeground(new java.awt.Color(204, 0, 0));
        p2_star4.setText("*");

        p2_type.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p2_type.setForeground(new java.awt.Color(204, 204, 204));
        p2_type.setText("Type");

        p2_typefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Children", "Senior Citizen", "Indian Armed Forces" }));
        p2_typefield.setMaximumSize(new java.awt.Dimension(32767, 0));
        p2_typefield.setPreferredSize(new java.awt.Dimension(96, 100));

        p2.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        p2.setText("Passenger 2");

        p3_star4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p3_star4.setForeground(new java.awt.Color(204, 0, 0));
        p3_star4.setText("*");

        p3_star.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p3_star.setForeground(new java.awt.Color(204, 0, 0));
        p3_star.setText("*");

        p3_star3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p3_star3.setForeground(new java.awt.Color(204, 0, 0));
        p3_star3.setText("*");

        p3_agefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", " " }));
        p3_agefield.setMaximumSize(new java.awt.Dimension(32767, 0));
        p3_agefield.setPreferredSize(new java.awt.Dimension(96, 100));

        p3.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        p3.setText("Passenger 3");

        p3_fname.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p3_fname.setForeground(new java.awt.Color(204, 204, 204));
        p3_fname.setText("First Name");

        jLabel41.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("Last Name");

        p3_type.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p3_type.setForeground(new java.awt.Color(204, 204, 204));
        p3_type.setText("Type");

        p3_star2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p3_star2.setForeground(new java.awt.Color(204, 0, 0));
        p3_star2.setText("*");

        p3_typefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Children", "Senior Citizen", "Indian Armed Forces" }));
        p3_typefield.setMaximumSize(new java.awt.Dimension(32767, 0));
        p3_typefield.setPreferredSize(new java.awt.Dimension(96, 100));

        p3_age.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p3_age.setForeground(new java.awt.Color(204, 204, 204));
        p3_age.setText("Age");

        p4_age.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p4_age.setForeground(new java.awt.Color(204, 204, 204));
        p4_age.setText("Age");

        p4_star3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p4_star3.setForeground(new java.awt.Color(204, 0, 0));
        p4_star3.setText("*");

        p4_type.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p4_type.setForeground(new java.awt.Color(204, 204, 204));
        p4_type.setText("Type");

        jLabel48.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 204, 204));
        jLabel48.setText("Last Name");

        p4_fname.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p4_fname.setForeground(new java.awt.Color(204, 204, 204));
        p4_fname.setText("First Name");

        p4.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        p4.setText("Passenger 4");

        p4_star2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p4_star2.setForeground(new java.awt.Color(204, 0, 0));
        p4_star2.setText("*");

        p4_star4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p4_star4.setForeground(new java.awt.Color(204, 0, 0));
        p4_star4.setText("*");

        p4_star.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        p4_star.setForeground(new java.awt.Color(204, 0, 0));
        p4_star.setText("*");

        p4_agefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", " " }));
        p4_agefield.setMaximumSize(new java.awt.Dimension(32767, 0));
        p4_agefield.setPreferredSize(new java.awt.Dimension(96, 100));

        p4_typefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Children", "Senior Citizen", "Indian Armed Forces" }));
        p4_typefield.setMaximumSize(new java.awt.Dimension(32767, 0));
        p4_typefield.setPreferredSize(new java.awt.Dimension(96, 100));

        jButton1.setBackground(new java.awt.Color(174, 29, 33));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox1)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p2_namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p2_star)
                                        .addGap(1, 1, 1)
                                        .addComponent(p2_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p2_star2)
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p2_lastfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p2_agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p2_star3)
                                        .addGap(1, 1, 1)
                                        .addComponent(p2_age, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p2_star4)
                                        .addGap(1, 1, 1)
                                        .addComponent(p2_type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p2_typefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p1_namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p1_star)
                                        .addGap(1, 1, 1)
                                        .addComponent(p1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p1_star2)
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p1_lastfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p1_agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p1_star3)
                                        .addGap(1, 1, 1)
                                        .addComponent(p1_age, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p1_star4)
                                        .addGap(1, 1, 1)
                                        .addComponent(p1_type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p1_typefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3_namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p3_star)
                                        .addGap(1, 1, 1)
                                        .addComponent(p3_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p3_star2)
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p3_lastfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3_agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p3_star3)
                                        .addGap(1, 1, 1)
                                        .addComponent(p3_age, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p3_star4)
                                        .addGap(1, 1, 1)
                                        .addComponent(p3_type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p3_typefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p4_namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p4_star)
                                        .addGap(1, 1, 1)
                                        .addComponent(p4_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p4_star2)
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p4_lastfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p4_agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p4_star3)
                                        .addGap(1, 1, 1)
                                        .addComponent(p4_age, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p4_star4)
                                        .addGap(1, 1, 1)
                                        .addComponent(p4_type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p4_typefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(8, 8, 8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p1_star2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p1_star))
                                        .addGap(8, 8, 8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(p1_namefield)
                                    .addComponent(p1_lastfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p1_type, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p1_star4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p1_typefield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p1_age, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p1_star3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p1_agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p2_star2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p2_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p2_star))
                                        .addGap(8, 8, 8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(p2_namefield)
                                    .addComponent(p2_lastfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p2_type, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p2_star4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p2_typefield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p2_age, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p2_star3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p2_agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p3_star2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p3_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p3_star))
                                        .addGap(8, 8, 8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(p3_namefield)
                                    .addComponent(p3_lastfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p3_type, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p3_star4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p3_typefield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p3_age, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p3_star3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p3_agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p4_star2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p4_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p4_star))
                                        .addGap(8, 8, 8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(p4_namefield)
                                    .addComponent(p4_lastfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p4_type, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p4_star4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p4_typefield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(p4_age, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p4_star3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p4_agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void disable()
{
       p2.setEnabled(false);
                p2_age.setEnabled(false);
                p2_agefield.setEnabled(false);
                p2_fname.setEnabled(false);
                p2_lastfield.setEnabled(false);
                p2_namefield.setEnabled(false);
                p2_star.setEnabled(false);
                p2_star2.setEnabled(false);
                p2_star3.setEnabled(false);
                p2_star4.setEnabled(false);
                p2_type.setEnabled(false);
                p2_typefield.setEnabled(false);
                
                   p1.setEnabled(false);
                p1_age.setEnabled(false);
                p1_agefield.setEnabled(false);
                p1_fname.setEnabled(false);
                p1_lastfield.setEnabled(false);
                p1_namefield.setEnabled(false);
                p1_star.setEnabled(false);
                p1_star2.setEnabled(false);
                p1_star3.setEnabled(false);
                p1_star4.setEnabled(false);
                p1_type.setEnabled(false);
                p1_typefield.setEnabled(false);
                
                   p3.setEnabled(false);
                p3_age.setEnabled(false);
                p3_agefield.setEnabled(false);
                p3_fname.setEnabled(false);
                p3_lastfield.setEnabled(false);
                p3_namefield.setEnabled(false);
                p3_star.setEnabled(false);
                p3_star2.setEnabled(false);
                p3_star3.setEnabled(false);
                p3_star4.setEnabled(false);
                p3_type.setEnabled(false);
                p3_typefield.setEnabled(false);
                
                   p4.setEnabled(false);
                p4_age.setEnabled(false);
                p4_agefield.setEnabled(false);
                p4_fname.setEnabled(false);
                p4_lastfield.setEnabled(false);
                p4_namefield.setEnabled(false);
                p4_star.setEnabled(false);
                p4_star2.setEnabled(false);
                p4_star3.setEnabled(false);
                p4_star4.setEnabled(false);
                p4_type.setEnabled(false);
                p4_typefield.setEnabled(false);
}
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        Main h = new Main();
//        System.out.println(h.passengers)
//        switch(h.passengers)
//        {
//            case "1":
//            {
//             disable();
//                 p1.setEnabled(true);
//                p1_age.setEnabled(true);
//                p1_agefield.setEnabled(true);
//                p1_fname.setEnabled(true);
//                p1_lastfield.setEnabled(true);
//                p1_namefield.setEnabled(true);
//                p1_star.setEnabled(true);
//                p1_star2.setEnabled(true);
//                p1_star3.setEnabled(true);
//                p1_star4.setEnabled(true);
//                p1_type.setEnabled(true);
//                p1_typefield.setEnabled(true); 
//            }break;
//            case "2":
//            {
//                  disable();
//                 p1.setEnabled(true);
//                p1_age.setEnabled(true);
//                p1_agefield.setEnabled(true);
//                p1_fname.setEnabled(true);
//                p1_lastfield.setEnabled(true);
//                p1_namefield.setEnabled(true);
//                p1_star.setEnabled(true);
//                p1_star2.setEnabled(true);
//                p1_star3.setEnabled(true);
//                p1_star4.setEnabled(true);
//                p1_type.setEnabled(true);
//                p1_typefield.setEnabled(true); 
//                  p2.setEnabled(true);
//                p2_age.setEnabled(true);
//                p2_agefield.setEnabled(true);
//                p2_fname.setEnabled(true);
//                p2_lastfield.setEnabled(true);
//                p2_namefield.setEnabled(true);
//                p2_star.setEnabled(true);
//                p2_star2.setEnabled(true);
//                p2_star3.setEnabled(true);
//                p2_star4.setEnabled(true);
//                p2_type.setEnabled(true);
//                p2_typefield.setEnabled(true);
//            }break;
//            case "3":
//            {
//                        p4.setEnabled(false);
//                p4_age.setEnabled(false);
//                p4_agefield.setEnabled(false);
//                p4_fname.setEnabled(false);
//                p4_lastfield.setEnabled(false);
//                p4_namefield.setEnabled(false);
//                p4_star.setEnabled(false);
//                p4_star2.setEnabled(false);
//                p4_star3.setEnabled(false);
//                p4_star4.setEnabled(false);
//                p4_type.setEnabled(false);
//                p4_typefield.setEnabled(false);
//            }break;
//            default:
//            {
//                
//            }
//        }
    }//GEN-LAST:event_formWindowOpened

    private void p2_agefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2_agefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2_agefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Custom_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Custom_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Custom_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Custom_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Custom_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p1_age;
    private javax.swing.JComboBox<String> p1_agefield;
    private javax.swing.JLabel p1_fname;
    private javax.swing.JTextField p1_lastfield;
    private javax.swing.JTextField p1_namefield;
    private javax.swing.JLabel p1_star;
    private javax.swing.JLabel p1_star2;
    private javax.swing.JLabel p1_star3;
    private javax.swing.JLabel p1_star4;
    private javax.swing.JLabel p1_type;
    private javax.swing.JComboBox<String> p1_typefield;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p2_age;
    private javax.swing.JComboBox<String> p2_agefield;
    private javax.swing.JLabel p2_fname;
    private javax.swing.JTextField p2_lastfield;
    private javax.swing.JTextField p2_namefield;
    private javax.swing.JLabel p2_star;
    private javax.swing.JLabel p2_star2;
    private javax.swing.JLabel p2_star3;
    private javax.swing.JLabel p2_star4;
    private javax.swing.JLabel p2_type;
    private javax.swing.JComboBox<String> p2_typefield;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p3_age;
    private javax.swing.JComboBox<String> p3_agefield;
    private javax.swing.JLabel p3_fname;
    private javax.swing.JTextField p3_lastfield;
    private javax.swing.JTextField p3_namefield;
    private javax.swing.JLabel p3_star;
    private javax.swing.JLabel p3_star2;
    private javax.swing.JLabel p3_star3;
    private javax.swing.JLabel p3_star4;
    private javax.swing.JLabel p3_type;
    private javax.swing.JComboBox<String> p3_typefield;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p4_age;
    private javax.swing.JComboBox<String> p4_agefield;
    private javax.swing.JLabel p4_fname;
    private javax.swing.JTextField p4_lastfield;
    private javax.swing.JTextField p4_namefield;
    private javax.swing.JLabel p4_star;
    private javax.swing.JLabel p4_star2;
    private javax.swing.JLabel p4_star3;
    private javax.swing.JLabel p4_star4;
    private javax.swing.JLabel p4_type;
    private javax.swing.JComboBox<String> p4_typefield;
    // End of variables declaration//GEN-END:variables
}
